### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by serebit** [BuddiesOfBudgie/magpie#13]
# TODO

Not an exhaustive list.

## Features

- [x] Fullscreen toplevels (e1bf1ea)
- [x] DPI scaling
- [ ] Variable refresh rate
- [ ] Direct scanout
- [ ] Workspaces
- [ ] Window movement resistivity
- [ ] Basic tiling
- [ ] Unmanaged XWayland surfaces
- [ ] Screen recording
- [ ] Capnproto for RPC

### Upstream

- [x] [content-type-v1](https://wayland.app/protocols/content-type-v1) (c5691a555)
- [x] [cursor-shape-v1](https://wayland.app/protocols/cursor-shape-v1) (f2671f2)
- [ ] [ext-session-lock-v1](https://wayland.app/protocols/ext-session-lock-v1)
- [x] [fractional-scale-v1](https://wayland.app/protocols/fractional-scale-v1) (4375e71)
- [ ] [keyboard-shortcuts-inhibit-unstable-v1](https://wayland.app/protocols/keyboard-shortcuts-inhibit-unstable-v1)
- [x] [pointer-constraints-unstable-v1](https://wayland.app/protocols/pointer-constraints-unstable-v1) (569d020 and a336c85)
- [x] [security-context-v1](https://wayland.app/protocols/security-context-v1) (098bad0)
- [ ] [tablet-unstable-v2](https://wayland.app/protocols/tablet-unstable-v2)
- [ ] [tearing-control-v1](https://wayland.app/protocols/tearing-control-v1)
- [ ] [xdg-decoration-unstable-v1](https://wayland.app/protocols/xdg-decoration-unstable-v1)
- [ ] [xdg-toplevel-drag-v1](https://wayland.app/protocols/xdg-toplevel-drag-v1)

### Wlroots

- [x] wlr-foreign-toplevel-v1
  - [x] events.request_fullscreen (e1bf1ea)
  - [x] events.request_close (c7cf1b062)
  - [x] events.set_rectangle (f81b8f858)
  - [x] output_enter (89e4d68a7 and 8911cb8b3)
  - [x] output_leave (89e4d68a7)
- [ ] wlr-input-inhibitor
- [x] wlr-output-management-unstable-v1 (e18d367 and dd6713b51)

### Other

- [ ] gtk-shell
- [ ] ext-workspace-unstable-v1

## Bugs

- [ ] Popup positioning
- [ ] Output area reset on size change

**Comment by JoshStrobl** [comment]
@serebit re experiments with popovers, we need to implement a mechanism where clicking outside the popover would "destroy" its surface and (optionally) propagate the click event.

**Comment by fossfreedom** [comment]
@serebit - for a screenlocker like swaylock we need also to think about these protocols

![image](https://github.com/BuddiesOfBudgie/magpie/assets/996240/f888a4d1-7c88-4805-b850-9f885a9d215d)

**Comment by serebit** [comment]
595aa39 adds an UNTESTED mechanism for layer_shell layer focus. Let me know if it's broken.
